
export ZSH="$HOME/.oh-my-zsh"

export PATH="$HOME/dotfiles/bin:$PATH"

ZSH_THEME="bira"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# Aliases
alias _="sudo"
alias la="ll -al"
alias rmf="rm -rf"
alias cls="clear"
